apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: inventory-dest
  name: default-view
  namespace: inventory-prod
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/inventory-src/rolebindings/default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
