apiVersion: v1
data:
  POSTGRES_DB: inventory
  POSTGRES_PASSWORD: inventory
  POSTGRES_USER: inventory
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"POSTGRES_DB":"inventory","POSTGRES_PASSWORD":"inventory","POSTGRES_USER":"inventory"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"postgres-config","namespace":"inventory"}}
  labels:
    app: postgres
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:POSTGRES_DB: {}
        f:POSTGRES_PASSWORD: {}
        f:POSTGRES_USER: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-02-24T19:26:50Z"
  name: postgres-config
  namespace: inventory
