apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1URXlNekl6TXpNeE5Wb1hEVE14TVRFeU1qSXpNek14TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzJ0ClYxVGlqOFRjd2pjVE11ZGJqQnQzaGdWR241Q2ozemt2RjRQMEZ2TmhnQTloZVdQM0wvblBzanYzN2VRUElWV3EKOEJLRDR0MzhrazhHRGRvdzRSYURSYVlhejY5b1oxYmlacW5vOTl3Z3lVTUR5MkpWSVBFS3p1anNyeWQraUFoVgpPNlpjZ3ZoU21mZ2lZVWpjYmtNK0s4OFYzcmlnY0FSdWVpa0FYa09BM004dHpGN20vckI0VEJqVWpFeW52YTF3CmF3NUVpekVxdjhZSEtwVjRtTG1PbE9qclgvY1FCa0hIOGR4OTFVTnRWOEdmSVpGNFNsYnB2Z0VJS2ppRVRXNTIKOXo3c29UYUpxdEpuTkdpL2xDeUlNMmNSbTNBeXpNQjBJeDAwOEpqU3hQWHVOTXZ5Z2d2NjhlN2M5bjNsUXpaeApGTHVSRXl4VDMyUzRsZjFOZHI4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUdTRHc0JZZnIzR1RZZmlQY241bTlKcmgzK2NEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRbDhjblQyRApzOHhJbzllK3pqM0tCRy81YnRkdkFla29LOU5RSnN2Z1Bzem9pZXN1OWNQRkhDVUs0Ni9MVU1KZnZkTWRVK2JuCmNsdU1mVVlrV0M5QzdUWm92c1RTd2M4TnpYZk81YS9mM25BMkRYd0huUTQ4eHhEc1FXWUpabUtHS2E4NllDMEcKTnNSSDBGNGZmQnlSMlhLSTlaUGRlNXpWMkZoc3dwSWM2cHlUZ2RSWTVzdGo0aVZBb3JQcHdGb253aGxLRHQ0ego2eXpwTG9zR0JpT3hXNXA5aDQ3VVQwZ2NXZjVjMTN6V0E5Ymw2NEhYYTlxaXROU1R0SFQ1bzZNcUZoZ1ZKZWVWClIvSTdFMjdIY1luYlp6L0U5ZVRKYS9IcGJtcWVRQzV2M2tqSG1VQytXa1FqNEhicGVuY0dPeHdPanNIMjBmeFcKS2tjcDNQdWdYQTdkbHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: aW52ZW50b3J5
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltUnpaR3gxV205M1psUnZTVFpMTlVOcFV6a3RWVWxrVWpCT2RuQjZhMGw2UzFGblR6UkdhREJyVGtVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpwYm5abGJuUnZjbmtpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMDNhelF5YWlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTUdWaVl6VmtZMk10WTJFeU9TMDBOelppTFdFM1lXTXRPRFUzTlRVMll6ZGxOemt6SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tbHVkbVZ1ZEc5eWVUcGtaV1poZFd4MEluMC5tUjluUVBLWTBDTHdHb2JhNGRxeDJKNlM5d0xYdjI0NTFmbngyLXJPckJNRjV0RDVzdERHZGYtZWRsZFE2ZUJ4VFVYd1lZcW0zOVc5V2ZlMDZzVkFrNUFzaXZQcFI3NW52WVd3Vk10MGUxVGhaZDdjTjR0bFFFMFdIWE5YbFI1aW5HRXkwWmxqbjZydno2R1NmUHZfX1c0ZkhWYXFEWTd4MnJ3M0tSNGI0eURpYXBKZXUybDk3RElUYUdUbGc4SGJVMy1vYVNRd3otZmVYeTFFTnJOVDdfcllqclBqbVVzNXRFQlNyX0FlYnBvNmlFUGRTR3Mza0xQT1VsUGpNRlc4alhSa202dXkxUGtEUVJNV0FBeldXS29PTFp0X2VMZ2FTYjMzNmdGbUl4bU1mVWQxU3d2N1M3SEhoa3dRXzY4cHhpWkRRdVJsNnl3XzB5dWpGQVhQTlE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 0ebc5dcc-ca29-476b-a7ac-857556c7e793
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-24T19:26:32Z"
  name: default-token-7k42j
  namespace: inventory
type: kubernetes.io/service-account-token
