apiVersion: v1
data:
  application.yaml: cXVhcmt1czoKICBkYXRhc291cmNlOgogICAgdXNlcm5hbWU6IGludmVudG9yeQogICAgcGFzc3dvcmQ6IGludmVudG9yeQo=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: inventory
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2022-02-24T21:58:23Z"
  name: inventory-secret
  namespace: inventory
type: Opaque
